codes:
  - python:
      settings:
      parameters:
        Aperture_horizontalSize:
          min: 0.995
          max: 1.005
          samples: 100
          start: 1
        Aperture_verticalSize:
          min: 0.995
          max: 1.005
          samples: 100
          start: 1
      setup:
        input_file: NSLS-II-CSX-1-beamline-rsOptExport.py
        function: set_rsopt_params_dummy
        execution_type: parallel
options:
  software: lh_scan
  seed: 
  nworkers: 1
  batch_size: 100
  output_file: NSLS-II-CSX-1-beamline-rsOptExport
  sim_dirs_make: False

