codes:
  - python:
      settings:
      parameters:
        Aperture_size_0:
          min: 0.9945
          max: 1.0055
          samples: 10
          start: 1
        Aperture_size_1:
          min: 0.995
          max: 1.005
          samples: 10
          start: 1
      setup:
        input_file: NSLS-II-CSX-1-beamline-rsOptExport.py
        function: set_rsopt_params_dummy
        execution_type: parallel
options:
  software: lh_scan
  nworkers: 1
  batch_size: 10
  run_dir: NSLS-II-CSX-1-beamline-rsOptExport_scan
  output_file: NSLS-II-CSX-1-beamline-rsOptExport
  sim_dirs_make: False

