name : tests

on:
  push:
  pull_request:

jobs:
  generate_conda_packd_envs:
    name: Generate conda-pack'd envs with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7,3.8,3.9]
      fail-fast: false
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "conda-pack"
          auto-update-conda: true
          miniconda-version: "latest"
          python version: ${{ matrix.python-version }}

      - name: start Sirepo-Bluesky docker container
        run: bash start_docker.sh -d

      - name: is Sirepo-Bluesky docker container running?
        run: docker ps -a

      - name: pip-install dependencies
        shell: bash -l {0}
        run: |
          set -vxeuo pipefail
          python3 -m pip install -r requirements.txt
    
      - name: pip-install dev-dependencies
        run: |
          set -vxeuo pipefail
          python3 -m pip install -r requirements-dev.txt

      - name: check env
        shell: bash -l {0}
        run: |
          set -vxeuo pipefail
          conda info
          conda env list
          conda list
          pip list
          conda config --show-sources
          conda config --show
          printenv | sort    

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          set -vxeuo pipefail
          source $CONDA/etc/profile.d/conda.sh
          conda activate test
          pytest -s -v deep_beamline_simulation/tests
