name : tests

on:
  push:
  pull_request:

jobs:
  DBS_tests:
    name: Test DBS with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7,3.8]
      fail-fast: false
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: start Sirepo-Bluesky container
        run: |
          set -vxeuo pipefail
          . scripts/start_sirepo.sh -d
          export SIREPO_DOCKER_CONTAINER_ID
          echo "SIREPO_DOCKER_CONTAINER_ID=${SIREPO_DOCKER_CONTAINER_ID}" >> $GITHUB_ENV

      - name: Is Sirepo-Bluesky docker container running?
        run: docker ps -a

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create conda environment
        run: |
          set -vxeuo pipefail
          source $CONDA/etc/profile.d/conda.sh
          conda create -n dbs python=${{ matrix.python-version }}

      - name: pip-install dependencies
        run: |
          set -vxeuo pipefail
          source $CONDA/etc/profile.d/conda.sh
          conda activate dbs
          conda env list
          pip install .
          pip install -r requirements-dev.txt
          conda install pytorch torchvision torchaudio cpuonly -c pytorch
          pip list
          conda list

      - name: Test with pytest
        run: |
          set -vxeuo pipefail
          source $CONDA/etc/profile.d/conda.sh
          conda activate dbs
          pytest -s -v
